### ISSUE TITLE
(Possible) incorrect use of readable stream

### ISSUE THREAD

**Issue by rahulreddy** [scality/sproxydclient#101]
https://github.com/scality/sproxydclient/blob/rel/6.2.5/lib/sproxyd.js#L191

Shouldn't this be
```js
stream.on('end', () => request.end());
```
?

**Comment by LaurenSpiegel** [comment]
I don't think this is necessary.  pipe takes care of this for you.

readable.pipe(destination[, options])#

Added in: v0.9.4
destination <stream.Writable> The destination for writing data
options <Object> Pipe options
end <Boolean> **End the writer when the reader ends. Defaults to true.**

This line should be removed and per the other issue, the log should be in the finish event.

**Comment by LaurenSpiegel** [comment]
Fixed by #102
