### ISSUE TITLE
Change the default sproxyd keys COS

### ISSUE THREAD

**Issue by vrancurel** [scality/sproxydclient#91]
The keys is currently set to COS='70' which seems to be problematic at some point because it interacts with the RING GC mechanism.

Although the problem has been fixed on the RING, changing the COS to '20' allows us to be compliant with older versions of the RING.

**Comment by DavidPineauScality** [comment]
Is this only the bit that generates the key, and thus should have no backwards compatibility issue ?

**Comment by vrancurel** [comment]
Potential issue with backup

**Comment by vrancurel** [comment]
Fixed with RING versions 6.4.0, 6.3.1, 5.1.9
Anyways keys can still conflict (minor) but advice from Eng is not use 70 at all.
